# Generated by Django 5.0.6 on 2024-06-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('series', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('chasis_num', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
